### ISSUE TITLE
Pressing Tab on the message console, goes to the next field

### ISSUE THREAD

**Issue by shivamgly** [mhgolkar/Weasel#2]
Right now if you press the Tab button it goes to the next field. It would be a good improvement if pressing Tab indents the line.

BTW I have injected a custom script provided [here](https://stackoverflow.com/questions/6637341/use-tab-to-indent-in-textarea) using TemperMonkey to add this feature, it works fine.

Also, Thanks for making the tool.

**Comment by mhgolkar** [comment]
Hi @shivamgly 

The new update (v2.1.1) captures tab button press and inserts a `\t` character.
It naturally prevents default functionality of the tab button (i.e. jumping to the next element) *only* when focus is on the message input. We can use `Ctrl + Alt + Shift + Tab` to compensate for that.
