### ISSUE TITLE
Feature: Ability to connect to self signed certificated wss server

### ISSUE THREAD

**Issue by DiedByDisgust** [mhgolkar/Weasel#3]
as in title, very self explained.

**Comment by mhgolkar** [comment]
Hello there!

Weasel already does have that ability. In better words: your browser does.
In terms of connectivity and security features, Weasel inherits everything from your browser.
We don't need really to reinvent a very good working wheel.

Modern browsers avoid self-signed certificates *by default* for security reasons.
You should tell them that you know what you're doing, and they should trust that very certificate.

Here is how you can do it in *Firefox* (~ v.116.x.x):

1. Head to **Privacy and Security** settings (i.e. `about:preferences#privacy`)
2. Find **Certificates** section and press ***View Certificates***
3. In the opened popup, switch to the **Servers** tab
4. Press ***Add Exception***
5. Enter your server's *location* where the cert can be fetched from, then press ***Get Certificate***  
    NOTE: You probably need to use `https://` here instead of `wss://` to make it work.
6. You can now view and ***Confirm Security Exception***
7. **OK** and you're done!

I hope you find it helpful.
